name: many_lints
description: "A comprehensive collection of custom lint rules, quick fixes, and code assists for Flutter and Dart projects."
version: 0.5.0
homepage: https://nikoro.github.io/many_lints
documentation: https://nikoro.github.io/many_lints/docs
repository: https://github.com/Nikoro/many_lints
issue_tracker: https://github.com/Nikoro/many_lints/issues
topics: [lint, lints, linter, analyzer, code]

environment:
  sdk: ^3.11.0

dependencies:
  analyzer: ^13.3.0
  analyzer_plugin: ^0.14.12
  analysis_server_plugin: ^0.3.18

dev_dependencies:
  test: ^1.31.1
  analyzer_testing: ^0.3.2
  test_reflective_loader: ^0.4.0
  lints: ^6.1.0
